version: "3"
services:
    mongodb:
        image: mongo
        restart: always
        ports:
          - "27017:27017"
        environment:
          - MONGO_INITDB_DATABASE="craft"
        volumes:
          - ./mongo-volume:/data/db
          - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro  
    app:
      build: .
      ports:
        - "8080:8080"
      depends_on: 
        - mongodb
